export const listaDeRutas = [
    ['Bicicletas', '/bicicletas-por-marca', 'Bicicletas por marca'],
    ['Bicicletas', '/de-ruta', 'Bicicletas de ruta'],
    ['Bicicletas', '/de-montana', 'Mountain bikes'],
    ['Bicicletas', '/active', 'Active bikes'],
    ['Bicicletas', '/ninos', 'Para niños'],
    ['Bicicletas', '/electricas', 'Eléctricas'],
    ['Componentes', '/brakes', 'Brakes'],
    ['Componentes', '/chains-and-cassettes', 'Chains & cassettes'],
    ['Componentes', '/cranksets-and-bottom-brackets', 'Cranksets & bottom brackets'],
    ['Componentes', '/derailleurs-and-shifters', 'Derailleurs & shifters'],
    ['Componentes', '/frame-parts', 'Frame parts'],
    ['Componentes', '/forks-headsets-stems-shocks', 'Forks / headsets / stems / shocks'],
    ['Componentes', '/handlebars-and-grips', 'Handlebars & grips'],
    ['Componentes', '/maintenance', 'Maintenance'],
    ['Componentes', '/pedals-and-cleats', 'Pedals and cleats'],
    ['Componentes', '/saddles-and-seatposts', 'Saddles & seatposts'],
    ['Componentes', '/wheels-and-tires', 'Wheels & tires'],
    ['Aparejos', '/aparejos-por-marca', 'Aparejos por marca'],
    ['Aparejos', '/tops', 'Tops'],
    ['Aparejos', '/bottoms', 'Bottoms'],
    ['Aparejos', '/apparel-accesories', 'Accesorios'],
    ['Aparejos', '/cascos', 'Cascos'],
    ['Aparejos', '/shoes', 'Shoes'],
    ['Accesorios', '/electronics', 'Electronics'],
    ['Accesorios', '/hydratation', 'Hydratation'],
    ['Accesorios', '/storage-and-travel', 'Storage & travel'],
    ['Accesorios', '/safety-and-security', 'Safety & security'],
    ['Accesorios', '/health-and-recovery', 'Health & recovery'],
    ['Accesorios', '/trailers-and-strollers', 'Trailers & strollers'],
    ['Accesorios', '/trainers', 'Trainers'],
    ['Accesorios', '/media-and-resources', 'Media & resources']
];

