export const listaDeRutas = [
    ['/bicicletas-por-marca', 'Bicicletas por marca'],
    ['/de-ruta', 'Bicicletas de ruta'],
    ['/de-montana', 'Mountain bikes'],
    ['/active', 'Active bikes'],
    ['/ninos', 'Para niños'],
    ['/electricas', 'Eléctricas'],
    ['/brakes', 'Brakes'],
    ['/chains-and-cassettes', 'Chains & cassettes'],
    ['/cranksets-and-bottom-brackets', 'Cranksets & bottom brackets'],
    ['/derailleurs-and-shifters', 'Derailleurs & shifters'],
    ['/frame-parts', 'Frame parts'],
    ['/forks-headsets-stems-shocks', 'Forks / headsets / stems / shocks'],
    ['/handlebars-and-grips', 'Handlebars & grips'],
    ['/maintenance', 'Maintenance'],
    ['/pedals-and-cleats', 'Pedals and cleats'],
    ['/saddles-and-seatposts', 'Saddles & seatposts'],
    ['/wheels-and-tires', 'Wheels & tires'],
    ['/aparejos-por-marca', 'Aparejos por marca'],
    ['/tops', 'Tops'],
    ['/bottoms', 'Bottoms'],
    ['/apparel-accesories', 'Accesorios'],
    ['/cascos', 'Cascos'],
    ['/shoes', 'Shoes'],
    ['/electronics', 'Electronics'],
    ['/hydratation', 'Hydratation'],
    ['/storage-and-travel', 'Storage & travel'],
    ['/safety-and-security', 'Safety & security'],
    ['/health-and-recovery', 'Health & recovery'],
    ['/trailers-and-strollers', 'Trailers & strollers'],
    ['/trainers', 'Trainers'],
    ['/media-and-resources', 'Media & resources']
];

